// =============================================================
// COCKTAIL DATA — Kiyori × Aki × Classics
// Cavendish Square, London · cocktail spec study
// Edit / extend entries below. The app reads this file on load.
// =============================================================
//
// Shape:
//   venue:    "Kiyori" | "Aki" | "Classics"   (top-level toggle)
//   category: filter pill within the venue
//   name, kanji, price, ingredients ...
//   hasNA: true   → shows a "N/A AVAILABLE" badge
//
// Kiyori cards use: prefecture, narrative, volume, method, glass, garnish, ice
// Aki cards use:    tastingNotes (array), ingredients, prep
// Classics use:     prep only
//

const cocktails = [

  // ─────────────────────────────────────────────────────────────
  // KIYORI BAR — Underground vault cocktail lounge beneath Aki
  // Source: kiyoribar.com/menu + on-site spec labels (May 2026)
  // ─────────────────────────────────────────────────────────────
  {
    venue: "Kiyori",
    name: "Sakura",
    kanji: "桜",
    category: "Signature",
    price: "£18",
    prefecture: "Kakunodate · Cherry Blossom",
    narrative: "Hanami — the traditional practice of enjoying the transient beauty of cherry blossoms.",
    ingredients: "Roku Japanese gin · Mancino Sakura · lychee blossom & orchid · sakura air foam",
    volume: "100ml Premix",
    method: "Build",
    glass: "Nick & Nora",
    garnish: "Sakura Coin",
    ice: "—",
    hasNA: false,
  },
  {
    venue: "Kiyori",
    name: "Hokkaido",
    kanji: "北海道",
    category: "Signature",
    price: "£18",
    prefecture: "Hokkaido · Snow · Sand · Sea",
    narrative: "Hokkaido Beach — Japan's most iconic shoreline, a tropical illusion in the north.",
    ingredients: "El Dorado 3yo · Etsu Ocean · pandan & kaffir · coconut · pineapple · turmeric",
    volume: "105ml",
    method: "Build",
    glass: "Coupe",
    garnish: "Caviar · Turmeric Foam",
    ice: "—",
    hasNA: false,
  },
  {
    venue: "Kiyori",
    name: "Torii",
    kanji: "鳥居",
    category: "Aperitif",
    price: "£14",
    prefecture: "Kyoto · Fushimi Inari",
    narrative: "1000 torii gates — a path through spirituality and quiet ceremony.",
    ingredients: "Aperitif house blend · sesame · orgeat & fig leaf soda",
    volume: "—",
    method: "Build",
    glass: "Highball",
    garnish: "Sesame cracker · spritz gel",
    ice: "Cubed",
    hasNA: true,
  },
  {
    venue: "Kiyori",
    name: "Maiko",
    kanji: "舞妓",
    category: "Aperitif",
    price: "£14",
    prefecture: "Kyoto · The Art of Geisha",
    narrative: "Entering the secretive world of Japan's geishas — restraint, elegance, ritual.",
    ingredients: "Sencha · vanilla · lychee · ginger · matcha air foam",
    volume: "—",
    method: "Shaken / Foam",
    glass: "H2 glass",
    garnish: "Matcha cookie leaf",
    ice: "—",
    hasNA: true,
  },
  {
    venue: "Kiyori",
    name: "Fuji-San",
    kanji: "富士山",
    category: "Premium",
    price: "£34",
    prefecture: "Chubu · Mount Fuji",
    narrative: "Japan's most iconic stratovolcano — coconut-oil-washed mezcal layered with mango.",
    ingredients: "Illegal mezcal (coconut oil washed) · coconut · mango · Muyu vetiver",
    volume: "130ml",
    method: "Stirred",
    glass: "Rock glass",
    garnish: "Kiyori orange stamp",
    ice: "Stamped ice cube",
    hasNA: false,
  },
  {
    venue: "Kiyori",
    name: "Womb",
    kanji: "渋谷",
    category: "Signature",
    price: "£24",
    prefecture: "Tokyo · Shibuya Nightlife",
    narrative: "Shibuya after dark — the pulse of Tokyo nightlife distilled into a glass.",
    ingredients: "Konik's Tail vodka · maraschino · vanilla · dill · honey melon",
    volume: "135ml",
    method: "Shaken",
    glass: "H2 glass",
    garnish: "—",
    ice: "Red & yellow colour ice ball",
    hasNA: false,
  },
  {
    venue: "Kiyori",
    name: "Seppuku",
    kanji: "切腹",
    category: "Premium",
    price: "£24",
    prefecture: "Kyoto · Samurai & Ninja Museum",
    narrative: "The samurai sword experience — ceremonial, considered, never chaotic.",
    ingredients: "Courvoisier & cherry wood–aged awamori · sesame · ginseng tea · absinthe",
    volume: "90ml Pre-mix",
    method: "Stirred",
    glass: "H₂O Water glass",
    garnish: "Ginseng jelly · Katana",
    ice: "—",
    hasNA: false,
  },
  {
    venue: "Kiyori",
    name: "Koshu",
    kanji: "古酒",
    category: "Premium",
    price: "£20",
    prefecture: "Tokyo · Akihabara District",
    narrative: "Centre of Japan's otaku culture — smoky, umami-adjacent, the second sip better than the first.",
    ingredients: "Suntory Toki whisky · smoked El Gobernador pisco · shiso · yuzu liqueur",
    volume: "100ml",
    method: "Stirred",
    glass: "Rock / Stamped",
    garnish: "Kiyori orange stamp · grape pickle",
    ice: "Cubed",
    hasNA: false,
  },
  {
    venue: "Kiyori",
    name: "Kawaii",
    kanji: "可愛い",
    category: "Signature",
    price: "—",
    prefecture: "Japan · Pop Culture",
    narrative: "Cute, playful, theatrical — a smoke-bubble serve that delights before the first sip.",
    ingredients: "House pre-mix — ask the bar for tonight's build",
    volume: "140ml Pre-Mix",
    method: "Shaken / Smoke Bubble",
    glass: "Triangle Porcelain",
    garnish: "Smoke bubble",
    ice: "—",
    hasNA: false,
  },

  // ─────────────────────────────────────────────────────────────
  // AKI BAR — Ground-floor restaurant bar
  // Botanical categories: Sakura, Yuzu, Sancho, Green Tea, Ume, Soy
  // Each pair: Alcoholic + Non-alcoholic
  // ─────────────────────────────────────────────────────────────
  {
    venue: "Aki",
    name: "Hanagasum (Blossom Mist)",
    kanji: "桜",
    category: "Sakura",
    price: "£17",
    tastingNotes: ["floral", "fruity", "fizzy"],
    ingredients: "Roku Sakura Gin, Blossom Tea Liq, Sweet & Sour, Saline Solution, Fig Leaf Soda",
    prep: "50ml Pre Mix, Top Up Fig Leaf Soda, Long Rocks, Column Ice, Sakura Stamp.",
    hasNA: false,
  },
  {
    venue: "Aki",
    name: "Hana Fubuki (Flower Snowstorm)",
    kanji: "桜",
    category: "Sakura",
    price: "£14",
    tastingNotes: ["floral", "tangy", "fizzy"],
    ingredients: "Blossom Shrub, Orange Water, Fig Leaf Soda",
    prep: "25ml Premix (Red color), Top Fig Leaf Soda, Long Rocks, Column ice with Sakura stamp.",
    hasNA: true,
  },
  {
    venue: "Aki",
    name: "Yuzukō (Yuzu Light)",
    kanji: "柚",
    category: "Yuzu",
    price: "£17",
    tastingNotes: ["green sugar cane", "yuzu", "vibrant"],
    ingredients: "Bacardi Carta Blanco Rum, El Dorado 3 Rum, La Yuzu Liqueur, Lime Juice, Grapefruit Bitters, Yuzu Air Foam",
    prep: "75 ml Pre Mix, Nick & Nora Glass, Yuzu Foam, Grated Lemon.",
    hasNA: false,
  },
  {
    venue: "Aki",
    name: "Yuzubai (Roasted Yuzu)",
    kanji: "柚",
    category: "Yuzu",
    price: "£14",
    tastingNotes: ["roasted", "silky citrus", "fizzy"],
    ingredients: "Tanqueray 0.0 Infused Coffee Bean, Coffee Cordial, Homemade Yuzu Soda",
    prep: "Coffee Tanq Inf 40ml, Amazake Coffee 60ml, Yuzu water 70ml. Shake & double strain, Top soda, Tall Rocks and Column Sakura ice.",
    hasNA: true,
  },
  {
    venue: "Aki",
    name: "Tōkaiden (Spicy Electric Current)",
    kanji: "山椒",
    category: "Sancho",
    price: "£18",
    tastingNotes: ["grassy", "citrusy", "smooth"],
    ingredients: "Tapatio Blanco Tequila Infused Kaffir Lime Leaves & Lemongrass, La Okinawa Citrus Liqueur, Sansho Leaves Cordial, Japanese Bitters",
    prep: "90ml premix, Small Rocks Glass, Ice Block, Sancho Leaf.",
    hasNA: false,
  },
  {
    venue: "Aki",
    name: "Ha No Kaori (Fragrance of the Leaf)",
    kanji: "山椒",
    category: "Sancho",
    price: "£14",
    tastingNotes: ["fruity", "peppery", "tangy"],
    ingredients: "Sansho Pepper Cordial, Coconut Water, Honey & Passion Fruit, Lime Juice",
    prep: "90ml premix, rocks glass, lime garnish.",
    hasNA: true,
  },
  {
    venue: "Aki",
    name: "Midori No Michi (The Green Path)",
    kanji: "茶",
    category: "Green Tea",
    price: "£18",
    tastingNotes: ["herbal", "earthy", "evolutive"],
    ingredients: "Haku Japanese Vodka, Green Tea Vermouth, Italicus, Absinth Drop, Matcha Ice Ball",
    prep: "Build, 100 premix, Coupe Glass, Matcha ice ball, Matcha leaf.",
    hasNA: false,
  },
  {
    venue: "Aki",
    name: "Ryokun / Ryokan (Green Cloud)",
    kanji: "茶",
    category: "Green Tea",
    price: "£14",
    tastingNotes: ["vegetal", "tropical", "tartness"],
    ingredients: "Green Tea Cordial, Pineapple & Galangal Juice, Coconut Water, Matcha Foam",
    prep: "80ml Premix, Rocks Glass, Ice Block, Dehydrated wheel.",
    hasNA: true,
  },
  {
    venue: "Aki",
    name: "Umebiki (Sake Draw)",
    kanji: "梅",
    category: "Ume",
    price: "£17",
    tastingNotes: ["stone fruit", "fresh", "fizzy"],
    ingredients: "Akashi Tai Sake Umeshu, Italicus, Plum & Shiso Reduction, Sparkling Wine, Plum Bitters, Plum Air Foam",
    prep: "Build, 60ml Premix, Top Up Prosecco 90ml, Wine Glass/Ice Ball, Plum Foam, Plum Jelly.",
    hasNA: false,
  },
  {
    venue: "Aki",
    name: "Umeshu Shines (Umeshu's Star)",
    kanji: "梅",
    category: "Ume",
    price: "£18",
    tastingNotes: ["candied plum", "light smoke", "astringent"],
    ingredients: "Matsui Umeshu, Honey & Sudachi Sour Mix, Laphroaig, Old-Fashioned Bitters",
    prep: "80ml premix, rocks glass, ice block, lemon zest.",
    hasNA: false,
  },
  {
    venue: "Aki",
    name: "Hishio (Fermented Sauces)",
    kanji: "醤",
    category: "Soy",
    price: "£18",
    tastingNotes: ["bitter-sweet", "umami", "light citrus"],
    ingredients: "Bombay Sapphire, Etsu Double Orange, Mancino Rosso & Chinato Vermouth, Campari, Homemade Ponzu",
    prep: "Build, 100 premix, Rocks Glass / Block ice, Orange jelly, Sesame spray.",
    hasNA: false,
  },
  {
    venue: "Aki",
    name: "Mame-Mary",
    kanji: "醤",
    category: "Soy",
    price: "£17.50",
    tastingNotes: ["umami", "silky", "fizzy"],
    ingredients: "Grey Goose Vodka Infused Kaffir Lime, La Tomato Japanese Liq, Edamame & Coconut Syrup, Rice Vinegar & Tonkatsu Sauce, Tomato Soda",
    prep: "No specific prep label available on bar station.",
    hasNA: false,
  },

  // ─────────────────────────────────────────────────────────────
  // CLASSICS — UK bar standards (prep notes only)
  // ─────────────────────────────────────────────────────────────
  {
    venue: "Classics",
    name: "Clase Azul Mar",
    category: "Classic",
    prep: "65ml premix, martini glass, half salt.",
  },
  {
    venue: "Classics",
    name: "Rum Highball",
    category: "Classic",
    prep: "70ml premix, ice Column, top up soda, lemon zest.",
  },
  {
    venue: "Classics",
    name: "Lychee Martini",
    category: "Classic",
    prep: "Shaken. 50ml vodka, 20ml lychee liq, 10ml lemon juice, 10ml sugar syrup. Optional: Lychee skewers.",
  },
  {
    venue: "Classics",
    name: "Mimosa",
    category: "Classic",
    prep: "75ml Orange Juice, 75ml Prosecco, Champagne glass/flute. Optional: orange twist garnish.",
  },
  {
    venue: "Classics",
    name: "Margarita",
    category: "Classic",
    prep: "40ml tequila, 20ml cointreau, 20ml lime juice. Shaken / Rocks Glass, Block Ice.",
  },
  {
    venue: "Classics",
    name: "Old Fashioned",
    category: "Classic",
    prep: "80ml premix, rocks glass, ice block, Orange zest.",
  },
  {
    venue: "Classics",
    name: "Martini",
    category: "Classic",
    prep: "Shaken or stirred. 60ml gin or vodka, 5ml or 1 dash vermouth. Dilute till perfection! Garnish with olive if dirty, lemon if not. Add 5ml brine if dirty for flavour.",
  },
  {
    venue: "Classics",
    name: "Moscow Mule",
    category: "Classic",
    prep: "50ml Vodka, 20ml lime juice, Top Ginger beer, 2 dash angostura bitters. Rocks with Mint Sprig garnish.",
  },
  {
    venue: "Classics",
    name: "Daiquiri",
    category: "Classic",
    prep: "Shaken. 50ml White Rum, 20ml Lime juice, 15 sugar syrup. Coupe glass, dehydrated wheel.",
  },
  {
    venue: "Classics",
    name: "Negroni",
    category: "Classic",
    prep: "Stirred in Mixing glass. 25ml Gin, 25ml campari, 25ml sweet vermouth. Rocks Glass, Orange slice.",
  },
  {
    venue: "Classics",
    name: "Espresso Martini",
    category: "Classic",
    prep: "Shaken. 50ml vodka, 15 kahlua, 10ml sugar, 50ml fresh brewed coffee. Coupe glass, 3 espresso beans.",
  },

];
